import * as THREE from './vendor/three.module.js';
import {GLTFLoader} from './vendor/GLTFLoader.js';
import {RoundedBoxGeometry} from './vendor/RoundedBoxGeometry.js';
export function createRoomRenderer(element,getState,callbacks){
let editing=false,draft=[],selected=null,cottageTime='evening',gridVisible=true;
const kinds={sofa:'소파',desk:'책상',shelf:'선반',plant:'화분',rug:'러그',frame:'액자',cat:'고양이',calendar:'달력'};
const names={records:'기록',tasks:'할 일',calendar:'공유 일정',itinerary:'여행 일정',places:'장소',packing:'준비물',expenses:'정산',polls:'투표',activities:'이벤트'};
const footprintsByKind={sofa:[3,2],desk:[2,2],shelf:[2,1],plant:[1,1],cat:[1,1],frame:[1,1],rug:[3,2],calendar:[1,1]};
const space=()=>({room:draft}),toast=message=>callbacks.error(message);
const fits=(room,o,x,y)=>x>=0&&y>=0&&x+o.w<=8&&y+o.h<=8&&!room.some(t=>t.id!==o.id&&o.kind!=='rug'&&t.kind!=='rug'&&x<t.x+t.w&&x+o.w>t.x&&y<t.y+t.h&&y+o.h>t.y);
const move=(o,x,y)=>callbacks.move(o.id,x,y);
const loader=new GLTFLoader(), models=new Map(), materials=new Map();
let renderer,scene,camera,host,observer,aborter,generation=0,groups=new Map(),labels=[],tiles,drag=null;
const ray=new THREE.Raycaster(),mouse=new THREE.Vector2(),floorPlane=new THREE.Plane(new THREE.Vector3(0,1,0),0);
const modelFiles={sofa:'loungeSofa',desk:'desk',shelf:'bookcaseOpen',plant:'pottedPlant',rug:'rugRounded'};
const previews=new Map();let previewTask;

function fillPreviews(){callbacks.previews?.(Object.fromEntries(previews));}
async function buildPreviews(){if(previewTask)return previewTask;previewTask=(async()=>{const r=new THREE.WebGLRenderer({alpha:true,antialias:true,preserveDrawingBuffer:true});r.setSize(160,130);r.toneMapping=THREE.ACESFilmicToneMapping;r.toneMappingExposure=1.1;for(const kind of Object.keys(kinds)){const s=new THREE.Scene(),g=new THREE.Group();s.add(g);const [w,h]=footprintsByKind[kind];if(modelFiles[kind])await addModel(g,modelFiles[kind],w*.9,h*.85,{shelf:2.5,plant:1.65,rug:.06,sofa:1.3,desk:1.25}[kind]);else if(kind==='cat')cat(g);else frame(g,kind==='calendar');s.add(new THREE.HemisphereLight('#fff1dd','#af97b0',2.4));const key=new THREE.DirectionalLight('#ffdeb4',2.2);key.position.set(3,6,5);s.add(key);const box=new THREE.Box3().setFromObject(g),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3()),extent=Math.max(size.x,size.y,size.z)*.7+.12,c=new THREE.OrthographicCamera(-extent*160/130,extent*160/130,extent,-extent,.1,30);c.position.copy(center).add(new THREE.Vector3(5,4,5));c.lookAt(center);r.render(s,c);previews.set(kind,r.domElement.toDataURL('image/png'));g.traverse(o=>{if(o.geometry&&!o.userData.sharedGeometry)o.geometry.dispose();});}r.dispose();fillPreviews();})().catch(()=>{});return previewTask;}
const palette={wood:'#d1a174',woodDark:'#a67b58',metal:'#b7aaa0',metalDark:'#54566b',metalMedium:'#a6afb2',carpet:'#93738d',carpetDarker:'#b9878d',carpetWhite:'#f0dec0',plant:'#91aa78',plastic:'#e6dbc5',black:'#645c68',white:'#f2e6cc'};

function material(color){if(materials.has(color))return materials.get(color);const m=new THREE.MeshStandardMaterial({color,roughness:.92,metalness:0});
  // A warm lower-surface tint gives the matte objects a soft painted finish.
  m.onBeforeCompile=shader=>{shader.vertexShader='varying float vCozyHeight;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\nvCozyHeight=(modelMatrix*vec4(transformed,1.0)).y;');shader.fragmentShader='varying float vCozyHeight;\n'+shader.fragmentShader;shader.fragmentShader=shader.fragmentShader.replace('#include <color_fragment>','#include <color_fragment>\ndiffuseColor.rgb *= mix(vec3(1.06,0.97,0.89),vec3(1.0,1.0,1.0),smoothstep(0.0,2.8,vCozyHeight));');};m.customProgramCacheKey=()=> 'sai-cozy-matte-v1';materials.set(color,m);return m;}
function rounded(parent,w,h,d,color,x=0,y=h/2,z=0,r=.07){const mesh=new THREE.Mesh(new RoundedBoxGeometry(w,h,d,3,Math.min(r,w/3,h/3,d/3)),material(color));mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh;}
function sphere(parent,color,x,y,z,sx,sy=sx,sz=sx){const mesh=new THREE.Mesh(new THREE.SphereGeometry(1,16,12),material(color));mesh.position.set(x,y,z);mesh.scale.set(sx,sy,sz);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh;}
function getModel(file){if(!models.has(file))models.set(file,loader.loadAsync(new URL(`${import.meta.env.BASE_URL}room3d/models/${file}.glb`,window.location.origin).href).then(gltf=>gltf.scene));return models.get(file);}
async function addModel(parent,file,width,depth,maxHeight,position=[0,0,0]){const original=await getModel(file),object=original.clone(true),box=new THREE.Box3().setFromObject(object),size=box.getSize(new THREE.Vector3()),scale=Math.min(width/size.x,depth/size.z,maxHeight/size.y);object.scale.setScalar(scale);object.position.set(position[0]-(box.min.x+box.max.x)*scale/2,position[1]-box.min.y*scale,position[2]-(box.min.z+box.max.z)*scale/2);object.traverse(node=>{if(!node.isMesh)return;node.userData.sharedGeometry=true;const repaint=m=>material(palette[m.name]||'#d9c7b1');node.material=Array.isArray(node.material)?node.material.map(repaint):repaint(node.material);node.castShadow=true;node.receiveShadow=true;});parent.add(object);return object;}
function cat(parent){sphere(parent,'#f3e4cc',0,.23,0,.4,.22,.27);sphere(parent,'#f3e4cc',.27,.35,.03,.23,.23,.22);sphere(parent,'#806b83',-.25,.34,-.03,.2,.05,.18);for(const x of [.14,.39]){const ear=new THREE.Mesh(new THREE.ConeGeometry(.105,.21,3),material('#806b83'));ear.position.set(x,.56,.02);parent.add(ear);}sphere(parent,'#584b59',.2,.39,.22,.023);sphere(parent,'#584b59',.35,.39,.22,.023);sphere(parent,'#d59b92',.28,.34,.24,.026,.018,.018);const tail=new THREE.Mesh(new THREE.TorusGeometry(.2,.07,8,16,Math.PI*1.5),material('#806b83'));tail.rotation.x=Math.PI/2;tail.position.set(-.32,.15,.12);parent.add(tail);}
function frame(parent,calendar=false){rounded(parent,.75,.82,.08,'#bf936b',0,.48,0,.025);rounded(parent,.63,.69,.025,'#efe1c5',0,.48,.055,.01);if(calendar){for(let x=-.18;x<=.18;x+=.18)for(let y=.32;y<=.65;y+=.15)rounded(parent,.06,.06,.025,'#ad8ca1',x,y,.08,.008);}else{rounded(parent,.54,.36,.03,'#b5c9c1',0,.57,.08,.015);rounded(parent,.54,.2,.03,'#88a391',0,.3,.08,.015);sphere(parent,'#f0d4a1',.14,.66,.102,.07,.07,.01);}rounded(parent,.5,.06,.4,'#b78d65',0,.03,0,.02);parent.rotation.y=-Math.PI/8;}
function tile(o,color,opacity=.25){const mesh=new THREE.Mesh(new THREE.PlaneGeometry(o.w-.04,o.h-.04),new THREE.MeshBasicMaterial({color,transparent:true,opacity,depthWrite:false,side:THREE.DoubleSide}));mesh.rotation.x=-Math.PI/2;mesh.position.set(o.x+o.w/2,.03,o.y+o.h/2);return mesh;}
function updateTiles(){if(!tiles)return;for(const child of [...tiles.children]){child.geometry.dispose();child.material.dispose();tiles.remove(child);}if(editing)for(const o of draft)tiles.add(tile(o,o.id===selected?'#ac84c1':'#b69ea7',o.id===selected?.3:.09));}
function floorRoom(){const evening=cottageTime==='evening';rounded(scene,8.18,.24,8.18,'#bb9176',4,-.15,4,.08);for(let z=0;z<16;z++)for(let x=0;x<4;x++)rounded(scene,1.99,.08,.495,['#dabb98','#dfc29f','#d5b58f'][(x+z)%3],1+x*2,-.015,.25+z*.5,.008);
  // Two open walls keep all furniture visible from the fixed camera.
  const wallLeft=evening?'#c5a0b2':'#ead8bf',wallRight=evening?'#b1a4bc':'#c5d1bd';
  rounded(scene,.16,3.15,8.15,wallLeft,-.08,1.575,4,.03);rounded(scene,8.15,3.15,.16,wallRight,4,1.575,-.08,.03);rounded(scene,.19,.16,8.17,'#b79989',-.06,.12,4,.03);rounded(scene,8.17,.16,.19,'#b79989',4,.12,-.06,.03);
  // Window is a decorative wall panel with a gently lit sky.
  rounded(scene,.12,1.95,2.4,'#d6b391',.035,1.91,5.9,.025);const glass=new THREE.Mesh(new THREE.BoxGeometry(.035,1.71,2.16),new THREE.MeshStandardMaterial({color:evening?'#cfaabd':'#c2d9d1',emissive:evening?'#c7969f':'#b0c9bb',emissiveIntensity:.35,roughness:1}));glass.position.set(.12,1.91,5.9);scene.add(glass);rounded(scene,.08,1.78,.06,'#fff0d5',.15,1.91,5.9,.01);rounded(scene,.08,.06,2.2,'#fff0d5',.15,1.91,5.9,.01);rounded(scene,.35,.12,2.6,'#d9b591',.15,.92,5.9,.025);
  for(let i=0;i<6;i++){const x=2+i*.82,y=2.7-.25*Math.sin(i/5*Math.PI);sphere(scene,'#ffddb0',x,y,.17,.052);const bulb=scene.children.at(-1);bulb.material=new THREE.MeshStandardMaterial({color:'#ffe3ae',emissive:'#ffc57e',emissiveIntensity:evening?2:.2});const point=new THREE.PointLight('#ffcd93',evening?.55:.1,2,2);point.position.set(x,y,.35);scene.add(point);if(i){const prev=new THREE.Vector3(x-.82,2.7-.25*Math.sin((i-1)/5*Math.PI),.17),curr=new THREE.Vector3(x,y,.17),line=new THREE.Line(new THREE.BufferGeometry().setFromPoints([prev,curr]),new THREE.LineBasicMaterial({color:'#7d6778'}));scene.add(line);}}
  scene.add(new THREE.HemisphereLight('#fff1dc','#b6a0b5',evening?2:2.5));const sun=new THREE.DirectionalLight(evening?'#ffd6ac':'#fff0d2',evening?3:3.4);sun.position.set(-3,9,7);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-9;sun.shadow.camera.right=9;sun.shadow.camera.top=9;sun.shadow.camera.bottom=-9;sun.shadow.camera.near=.1;sun.shadow.camera.far=30;sun.shadow.bias=-.0004;sun.shadow.normalBias=.025;sun.shadow.radius=4;sun.target.position.set(4,0,4);scene.add(sun,sun.target);const fill=new THREE.DirectionalLight('#cbbfdf',1);fill.position.set(8,5,-2);scene.add(fill);
  if(editing&&gridVisible){const grid=new THREE.GridHelper(8,8,'#eedfca','#f0e2d2');grid.position.set(4,.055,4);grid.material.transparent=true;grid.material.opacity=.7;scene.add(grid);}tiles=new THREE.Group();scene.add(tiles);updateTiles();}
function paint(){if(!host?.isConnected||!renderer||!camera)return;renderer.render(scene,camera);const rect=host.getBoundingClientRect();for(const label of labels){const g=groups.get(label.o.id);if(!g)continue;const p=new THREE.Vector3(g.position.x,label.height,g.position.z).project(camera);label.button.style.left=`${(p.x*.5+.5)*rect.width}px`;label.button.style.top=`${(-p.y*.5+.5)*rect.height}px`;}}
function resize(){if(!host?.isConnected)return;const width=host.clientWidth,height=host.clientHeight,aspect=width/height,half=Math.max(5.2,5.9/aspect);camera.left=-half*aspect;camera.right=half*aspect;camera.top=half;camera.bottom=-half;camera.updateProjectionMatrix();renderer.setSize(width,height,false);paint();}
function pointer(e){const r=host.getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(mouse,camera);const point=new THREE.Vector3();return ray.ray.intersectPlane(floorPlane,point);}
function picked(e){pointer(e);const labeled=e.target.closest('[data-object]');if(labeled)return labeled.dataset.object;const hits=ray.intersectObjects([...groups.values()],true);for(const hit of hits){let object=hit.object;while(object&&!object.userData.objectId)object=object.parent;if(object?.userData.objectId)return object.userData.objectId;}return null;}
function selectObject(id){selected=id;updateTiles();callbacks.select(id);paint();}
async function mount(){const ticket=++generation;observer?.disconnect();aborter?.abort();host=element;if(!host.isConnected)return; host.replaceChildren();
  if(!renderer){try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;renderer.outputColorSpace=THREE.SRGBColorSpace;}catch{host.innerHTML='<p class="three-error">3D 화면을 열지 못했어요. 브라우저의 하드웨어 가속을 확인해주세요.</p>';return;}}
  if(scene)scene.traverse(o=>{o.shadow?.dispose();if(o.geometry&&!o.userData.sharedGeometry)o.geometry.dispose();if(o.material){const ms=Array.isArray(o.material)?o.material:[o.material];for(const m of ms)if(![...materials.values()].includes(m))m.dispose();}});
  scene=new THREE.Scene();camera=new THREE.OrthographicCamera();camera.position.set(15,12,15);camera.lookAt(4,1,4);groups=new Map();labels=[];host.append(renderer.domElement);renderer.domElement.setAttribute('aria-label','격자에 놓인 3D 가구와 우리 방');floorRoom();
  const room=editing?draft:space().room,tasks=[];
  for(const o of room){const group=new THREE.Group();group.userData.objectId=o.id;group.position.set(o.x+o.w/2,0,o.y+o.h/2);group.rotation.y=(o.rotation||0)*Math.PI/2;groups.set(o.id,group);scene.add(group);const quarter=(o.rotation||0)%2,baseW=quarter?o.h:o.w,baseH=quarter?o.w:o.h;
    let h={sofa:1.3,desk:1.25,shelf:2.5,plant:1.65,rug:.06,cat:.65,frame:1,calendar:1}[o.kind]||1;
    if(modelFiles[o.kind])tasks.push(addModel(group,modelFiles[o.kind],baseW*.9,baseH*.85,h).then(async()=>{if(o.kind==='desk'){await addModel(group,'laptop',.65,.45,.4,[0,1.13,-.1]);await addModel(group,'chairDesk',.65,.65,1.1,[0,0,.55]);}if(o.kind==='shelf'){await addModel(group,'books',.9,.3,.4,[0,.65,0]);await addModel(group,'plantSmall1',.5,.4,.5,[.3,2.2,0]);}if(o.kind==='sofa')await addModel(group,'pillow',.5,.35,.45,[.5,.55,0]);}).catch(()=>{if(ticket!==generation)return;rounded(group,baseW*.7,.7,baseH*.7,'#b792a1');toast('일부 가구를 불러오지 못했어요.');}));else if(o.kind==='cat')cat(group);else frame(group,o.kind==='calendar');
    const button=document.createElement('button');button.className='three-object-label '+(o.module?'functional':'decorative');button.dataset.object=o.id;button.setAttribute('aria-label',`${kinds[o.kind]} ${o.label||names[o.module]||'장식'}`);button.textContent=o.label||names[o.module]||kinds[o.kind];host.append(button);labels.push({o,button,height:h+.22});}
  observer=new ResizeObserver(resize);observer.observe(host);resize();aborter=new AbortController();const opts={signal:aborter.signal};
  host.addEventListener('pointerdown',e=>{if(!editing)return;const id=picked(e);if(!id)return;e.preventDefault();const o=draft.find(o=>o.id===id),p=pointer(e);selectObject(id);drag={o,id,p:p.clone(),x:o.x,y:o.y,nx:o.x,ny:o.y,startX:e.clientX,startY:e.clientY,moved:false};host.setPointerCapture(e.pointerId);},opts);
  host.addEventListener('pointermove',e=>{if(!drag)return;const p=pointer(e);if(!p)return;drag.moved ||=Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)>5;drag.nx=Math.round(drag.x+p.x-drag.p.x);drag.ny=Math.round(drag.y+p.z-drag.p.z);groups.get(drag.id).position.set(drag.nx+drag.o.w/2,0,drag.ny+drag.o.h/2);updateTiles();if(drag.moved)tiles.add(tile({...drag.o,x:drag.nx,y:drag.ny},fits(draft,drag.o,drag.nx,drag.ny)?'#8eb89a':'#d98c82',.5));paint();},opts);
  host.addEventListener('pointerup',()=>{if(!drag)return;if(drag.moved)move(drag.o,drag.nx,drag.ny);drag=null;update();},opts);host.addEventListener('pointercancel',()=>{drag=null;update();},opts);
  host.addEventListener('click',e=>{if(editing)return;const id=picked(e);if(!id)return;callbacks.open(id);},opts);
  await Promise.all(tasks);if(ticket===generation){host.dataset.ready='true';paint();buildPreviews().then(()=>{if(ticket===generation)fillPreviews();});}
}

function update(){const s=getState();editing=s.editing;draft=s.items;selected=s.selected;cottageTime=s.time;gridVisible=s.gridVisible;return mount();}
function dispose(){generation++;observer?.disconnect();aborter?.abort();if(scene)scene.traverse(o=>{o.shadow?.dispose();if(o.geometry&&!o.userData.sharedGeometry)o.geometry.dispose();});for(const m of materials.values())m.dispose();for(const promise of models.values())promise.then(model=>model.traverse(o=>{o.geometry?.dispose();const list=Array.isArray(o.material)?o.material:[o.material];list.forEach(m=>m?.dispose());}));renderer?.dispose();renderer?.forceContextLoss();element.replaceChildren();}
return {update,dispose};
}

